# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from ai_assistant.server.models.action_involved_elements import ActionInvolvedElements
from ai_assistant.server.models.action_user import ActionUser
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Action(BaseModel):
    """
    Actions describes what user has done on a single element or element's metadata. The user can add, edit or remove something. The \"something\" is described by the operation involved in the action, it can be an operation over an entity, a diagram, a hierarchy and so on. Reverting an action means reverting the operation that has been done and it depends on the type of the action. - Add => Remove - Remove => Add - Edit => restore the previous state of the subject of the operation made
    """ # noqa: E501
    operation_type: StrictStr = Field(alias="operationType")
    subject: Dict[str, Any]
    previous_state: Optional[Dict[str, Any]] = Field(default=None, alias="previousState")
    involved_elements: Optional[ActionInvolvedElements] = Field(default=None, alias="involvedElements")
    subactions: Optional[List[Action]] = None
    user: ActionUser
    timestamp: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["operationType", "subject", "previousState", "involvedElements", "subactions", "user", "timestamp"]

    @field_validator('operation_type')
    def operation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('add', 'edit', 'remove',):
            raise ValueError("must be one of enum values ('add', 'edit', 'remove')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Action from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of involved_elements
        if self.involved_elements:
            _dict['involvedElements'] = self.involved_elements.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in subactions (list)
        _items = []
        if self.subactions:
            for _item in self.subactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['subactions'] = _items
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Action from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operationType": obj.get("operationType"),
            "subject": obj.get("subject"),
            "previousState": obj.get("previousState"),
            "involvedElements": ActionInvolvedElements.from_dict(obj.get("involvedElements")) if obj.get("involvedElements") is not None else None,
            "subactions": [Action.from_dict(_item) for _item in obj.get("subactions")] if obj.get("subactions") is not None else None,
            "user": ActionUser.from_dict(obj.get("user")) if obj.get("user") is not None else None,
            "timestamp": obj.get("timestamp") if obj.get("timestamp") is not None else 0
        })
        return _obj

# TODO: Rewrite to not use raise_errors
Action.model_rebuild(raise_errors=False)

