# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.edge import Edge
from ai_assistant.server.models.hierarchy import Hierarchy
from ai_assistant.server.models.node import Node
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ActionInvolvedElements(BaseModel):
    """
    Other elements involved in an action. Only for Remove actions. The remove action on an Entity might involve other elements. i.e. object properties on removed classes
    """ # noqa: E501
    nodes: Optional[List[Node]] = None
    edges: Optional[List[Edge]] = None
    hierarchies: Optional[List[Hierarchy]] = Field(default=None, alias="Hierarchies")
    __properties: ClassVar[List[str]] = ["nodes", "edges", "Hierarchies"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActionInvolvedElements from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item in self.nodes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item in self.edges:
                if _item:
                    _items.append(_item.to_dict())
            _dict['edges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in hierarchies (list)
        _items = []
        if self.hierarchies:
            for _item in self.hierarchies:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Hierarchies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ActionInvolvedElements from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "nodes": [Node.from_dict(_item) for _item in obj.get("nodes")] if obj.get("nodes") is not None else None,
            "edges": [Edge.from_dict(_item) for _item in obj.get("edges")] if obj.get("edges") is not None else None,
            "Hierarchies": [Hierarchy.from_dict(_item) for _item in obj.get("Hierarchies")] if obj.get("Hierarchies") is not None else None
        })
        return _obj


