# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.describe_ontology_entity_request_property_info import DescribeOntologyEntityRequestPropertyInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DescribeOntologyEntityRequest(BaseModel):
    """
    DescribeOntologyEntityRequest
    """ # noqa: E501
    entity_name: StrictStr = Field(description="the name of the entity to describe", alias="entityName")
    entity_type: StrictStr = Field(alias="entityType")
    context: StrictStr = Field(description="the context in which the individual exists, most likely the name of the ontology")
    property_info: Optional[DescribeOntologyEntityRequestPropertyInfo] = Field(default=None, alias="propertyInfo")
    language: Optional[StrictStr] = Field(default='English', description="the language to use for the answer.")
    __properties: ClassVar[List[str]] = ["entityName", "entityType", "context", "propertyInfo", "language"]

    @field_validator('entity_type')
    def entity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('class', 'attribute', 'relationship',):
            raise ValueError("must be one of enum values ('class', 'attribute', 'relationship')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DescribeOntologyEntityRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of property_info
        if self.property_info:
            _dict['propertyInfo'] = self.property_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DescribeOntologyEntityRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entityName": obj.get("entityName"),
            "entityType": obj.get("entityType"),
            "context": obj.get("context"),
            "propertyInfo": DescribeOntologyEntityRequestPropertyInfo.from_dict(obj.get("propertyInfo")) if obj.get("propertyInfo") is not None else None,
            "language": obj.get("language") if obj.get("language") is not None else 'English'
        })
        return _obj


