# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.chart_configuration import ChartConfiguration
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DescribeChartRequest(BaseModel):
    """
    DescribeChartRequest
    """ # noqa: E501
    chart_configuration: ChartConfiguration = Field(alias="chartConfiguration")
    query_code: StrictStr = Field(description="the SPARQL code that generates the data for the chart", alias="queryCode")
    query_description: Optional[StrictStr] = Field(default=None, description="the description of the query to use. If not provided, LLM will generate one.", alias="queryDescription")
    language: Optional[StrictStr] = Field(default='English', description="the language to use for the answer.")
    __properties: ClassVar[List[str]] = ["chartConfiguration", "queryCode", "queryDescription", "language"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DescribeChartRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of chart_configuration
        if self.chart_configuration:
            _dict['chartConfiguration'] = self.chart_configuration.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DescribeChartRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chartConfiguration": ChartConfiguration.from_dict(obj.get("chartConfiguration")) if obj.get("chartConfiguration") is not None else None,
            "queryCode": obj.get("queryCode"),
            "queryDescription": obj.get("queryDescription"),
            "language": obj.get("language") if obj.get("language") is not None else 'English'
        })
        return _obj


