# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.element_ai_generated import ElementAiGenerated
from ai_assistant.server.models.position import Position
from ai_assistant.server.models.types_enum import TypesEnum
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Edge(BaseModel):
    """
    Edge
    """ # noqa: E501
    id: StrictStr
    original_id: Optional[StrictStr] = Field(default=None, description="In case of replicated elements, this is the ID of the original element replicated in multiple occurrences, all of them with different IDs", alias="originalId")
    diagram_id: Optional[StrictInt] = Field(default=0, alias="diagramId")
    displayed_name: Optional[StrictStr] = Field(default=None, alias="displayedName")
    iri: Optional[StrictStr] = None
    type: TypesEnum
    ai_generated: Optional[ElementAiGenerated] = Field(default=None, alias="aiGenerated")
    source_id: StrictStr = Field(alias="sourceId")
    target_id: StrictStr = Field(alias="targetId")
    breakpoints: Optional[List[Position]] = None
    domain_typed: Optional[StrictBool] = Field(default=True, alias="domainTyped")
    range_typed: Optional[StrictBool] = Field(default=True, alias="rangeTyped")
    domain_mandatory: Optional[StrictBool] = Field(default=False, alias="domainMandatory")
    range_mandatory: Optional[StrictBool] = Field(default=False, alias="rangeMandatory")
    __properties: ClassVar[List[str]] = ["id", "originalId", "diagramId", "displayedName", "iri", "type", "aiGenerated", "sourceId", "targetId", "breakpoints", "domainTyped", "rangeTyped", "domainMandatory", "rangeMandatory"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Edge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ai_generated
        if self.ai_generated:
            _dict['aiGenerated'] = self.ai_generated.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in breakpoints (list)
        _items = []
        if self.breakpoints:
            for _item in self.breakpoints:
                if _item:
                    _items.append(_item.to_dict())
            _dict['breakpoints'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Edge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "originalId": obj.get("originalId"),
            "diagramId": obj.get("diagramId") if obj.get("diagramId") is not None else 0,
            "displayedName": obj.get("displayedName"),
            "iri": obj.get("iri"),
            "type": obj.get("type"),
            "aiGenerated": ElementAiGenerated.from_dict(obj.get("aiGenerated")) if obj.get("aiGenerated") is not None else None,
            "sourceId": obj.get("sourceId"),
            "targetId": obj.get("targetId"),
            "breakpoints": [Position.from_dict(_item) for _item in obj.get("breakpoints")] if obj.get("breakpoints") is not None else None,
            "domainTyped": obj.get("domainTyped") if obj.get("domainTyped") is not None else True,
            "rangeTyped": obj.get("rangeTyped") if obj.get("rangeTyped") is not None else True,
            "domainMandatory": obj.get("domainMandatory") if obj.get("domainMandatory") is not None else False,
            "rangeMandatory": obj.get("rangeMandatory") if obj.get("rangeMandatory") is not None else False
        })
        return _obj


