# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class FunctionPropertiesEnum(str, Enum):
    """
    FunctionPropertiesEnum
    """

    """
    allowed enum values
    """
    FUNCTIONAL = 'functional'
    INVERSEFUNCTIONAL = 'inverseFunctional'
    TRANSITIVE = 'transitive'
    SYMMETRIC = 'symmetric'
    ASYMMETRIC = 'asymmetric'
    REFLEXIVE = 'reflexive'
    IRREFLEXIVE = 'irreflexive'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FunctionPropertiesEnum from a JSON string"""
        return cls(json.loads(json_str))


