# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GrapholscapeAnnotation(BaseModel):
    """
    GrapholscapeAnnotation
    """ # noqa: E501
    lexical_form: Optional[StrictStr] = Field(default=None, description="Has been renamed to `value`, kept for back-compatibility.", alias="lexicalForm")
    value: Optional[StrictStr] = None
    has_iri_value: Optional[StrictBool] = Field(default=False, alias="hasIriValue")
    var_property: StrictStr = Field(alias="property")
    language: Optional[StrictStr] = None
    datatype: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["lexicalForm", "value", "hasIriValue", "property", "language", "datatype"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GrapholscapeAnnotation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GrapholscapeAnnotation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lexicalForm": obj.get("lexicalForm"),
            "value": obj.get("value"),
            "hasIriValue": obj.get("hasIriValue") if obj.get("hasIriValue") is not None else False,
            "property": obj.get("property"),
            "language": obj.get("language"),
            "datatype": obj.get("datatype")
        })
        return _obj


