# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from ai_assistant.server.models.grapholscape_entity import GrapholscapeEntity
from ai_assistant.server.models.hierarchy_superclasses_inner import HierarchySuperclassesInner
from ai_assistant.server.models.types_enum import TypesEnum
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Hierarchy(BaseModel):
    """
    Hierarchy
    """ # noqa: E501
    id: StrictStr
    type: TypesEnum
    inputs: List[GrapholscapeEntity]
    superclasses: List[HierarchySuperclassesInner]
    __properties: ClassVar[List[str]] = ["id", "type", "inputs", "superclasses"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Hierarchy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in inputs (list)
        _items = []
        if self.inputs:
            for _item in self.inputs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['inputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in superclasses (list)
        _items = []
        if self.superclasses:
            for _item in self.superclasses:
                if _item:
                    _items.append(_item.to_dict())
            _dict['superclasses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Hierarchy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "inputs": [GrapholscapeEntity.from_dict(_item) for _item in obj.get("inputs")] if obj.get("inputs") is not None else None,
            "superclasses": [HierarchySuperclassesInner.from_dict(_item) for _item in obj.get("superclasses")] if obj.get("superclasses") is not None else None
        })
        return _obj


