# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.label import Label
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OntologyEntity(BaseModel):
    """
    OntologyEntity
    """ # noqa: E501
    entity_labels: Optional[List[Label]] = Field(default=None, alias="entityLabels")
    deprecated: Optional[StrictBool] = False
    entity_iri: StrictStr = Field(alias="entityIRI")
    entity_type: Optional[StrictStr] = Field(default=None, alias="entityType")
    entity_prefix_iri: Optional[StrictStr] = Field(default=None, alias="entityPrefixIRI")
    entity_remainder: Optional[StrictStr] = Field(default=None, alias="entityRemainder")
    entity_id: Optional[StrictStr] = Field(default=None, alias="entityID")
    __properties: ClassVar[List[str]] = ["entityLabels", "deprecated", "entityIRI", "entityType", "entityPrefixIRI", "entityRemainder", "entityID"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OntologyEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entity_labels (list)
        _items = []
        if self.entity_labels:
            for _item in self.entity_labels:
                if _item:
                    _items.append(_item.to_dict())
            _dict['entityLabels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OntologyEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entityLabels": [Label.from_dict(_item) for _item in obj.get("entityLabels")] if obj.get("entityLabels") is not None else None,
            "deprecated": obj.get("deprecated") if obj.get("deprecated") is not None else False,
            "entityIRI": obj.get("entityIRI"),
            "entityType": obj.get("entityType"),
            "entityPrefixIRI": obj.get("entityPrefixIRI"),
            "entityRemainder": obj.get("entityRemainder"),
            "entityID": obj.get("entityID")
        })
        return _obj


