# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OntologyCatalogEntryStatus(BaseModel):
    """
    The status of a given ontology catalog entry
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="The current status of the vector database.")
    error_message: Optional[StrictStr] = Field(default=None, description="The error message if the status is ERROR.", alias="errorMessage")
    percentage: Optional[StrictInt] = Field(default=None, description="The initialization progress percentage (0-100).")
    execution_time: Optional[StrictInt] = Field(default=None, description="The time taken for the last operation in milliseconds.", alias="executionTime")
    __properties: ClassVar[List[str]] = ["status", "errorMessage", "percentage", "executionTime"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('NOT_INITIALIZED', 'INITIALIZING', 'FINISHED', 'ERROR',):
            raise ValueError("must be one of enum values ('NOT_INITIALIZED', 'INITIALIZING', 'FINISHED', 'ERROR')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OntologyCatalogEntryStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OntologyCatalogEntryStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "errorMessage": obj.get("errorMessage"),
            "percentage": obj.get("percentage"),
            "executionTime": obj.get("executionTime")
        })
        return _obj


