# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.mwsx_ontology_catalog_entry import MWSXOntologyCatalogEntry
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OntologyCatalogHistoryEvent(BaseModel):
    """
    Represents an opeartion occurred on the ontology catalog
    """ # noqa: E501
    operation: Optional[StrictStr] = Field(default=None, description="the type of operation this ontology catalog event contains")
    timestamp: StrictInt = Field(description="the timestamp of the operation")
    ontology_catalog_entry: MWSXOntologyCatalogEntry = Field(alias="ontologyCatalogEntry")
    __properties: ClassVar[List[str]] = ["operation", "timestamp", "ontologyCatalogEntry"]

    @field_validator('operation')
    def operation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ADD', 'MOD', 'DEL',):
            raise ValueError("must be one of enum values ('ADD', 'MOD', 'DEL')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OntologyCatalogHistoryEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ontology_catalog_entry
        if self.ontology_catalog_entry:
            _dict['ontologyCatalogEntry'] = self.ontology_catalog_entry.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OntologyCatalogHistoryEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation": obj.get("operation"),
            "timestamp": obj.get("timestamp"),
            "ontologyCatalogEntry": MWSXOntologyCatalogEntry.from_dict(obj.get("ontologyCatalogEntry")) if obj.get("ontologyCatalogEntry") is not None else None
        })
        return _obj


