# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.rdf_graph import RDFGraph
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PutOntologyDraftAIRequest(BaseModel):
    """
    PutOntologyDraftAIRequest
    """ # noqa: E501
    text: Optional[StrictStr] = None
    current_rdf_graph: Optional[RDFGraph] = Field(default=None, alias="currentRdfGraph")
    iri_style: Optional[StrictBool] = Field(default=True, description="`True` for camelCase, `False` for snake_case", alias="iriStyle")
    simple_name_language: Optional[StrictStr] = Field(default='en', description="Language used for generating the variable part of entity IRIs. Value must be in ISO 2 chars format. Default \"en\"", alias="simpleNameLanguage")
    annotation_language: Optional[StrictStr] = Field(default='it', description="Language used for generating annotations on entities. Namely \"rdfs:label\" and \"rdfs:comment\". Value must be in ISO 2 chars format. Default \"it\"", alias="annotationLanguage")
    __properties: ClassVar[List[str]] = ["text", "currentRdfGraph", "iriStyle", "simpleNameLanguage", "annotationLanguage"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PutOntologyDraftAIRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_rdf_graph
        if self.current_rdf_graph:
            _dict['currentRdfGraph'] = self.current_rdf_graph.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PutOntologyDraftAIRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "currentRdfGraph": RDFGraph.from_dict(obj.get("currentRdfGraph")) if obj.get("currentRdfGraph") is not None else None,
            "iriStyle": obj.get("iriStyle") if obj.get("iriStyle") is not None else True,
            "simpleNameLanguage": obj.get("simpleNameLanguage") if obj.get("simpleNameLanguage") is not None else 'en',
            "annotationLanguage": obj.get("annotationLanguage") if obj.get("annotationLanguage") is not None else 'it'
        })
        return _obj


