# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.theme import Theme
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RDFGraphConfig(BaseModel):
    """
    RDFGraphConfig
    """ # noqa: E501
    themes: Optional[List[Theme]] = None
    selected_theme: Optional[StrictStr] = Field(default=None, alias="selectedTheme")
    language: Optional[StrictStr] = None
    entity_name_type: Optional[StrictStr] = Field(default=None, alias="entityNameType")
    renderers: Optional[List[StrictStr]] = None
    widgets: Optional[Dict[str, Any]] = None
    filters: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["themes", "selectedTheme", "language", "entityNameType", "renderers", "widgets", "filters"]

    @field_validator('entity_name_type')
    def entity_name_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('label', 'prefixed_iri', 'full_iri',):
            raise ValueError("must be one of enum values ('label', 'prefixed_iri', 'full_iri')")
        return value

    @field_validator('filters')
    def filters_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in ('all', 'data-property', 'value-domain', 'individual', 'annotation-property', 'universal_quantifier', 'complement', 'has-key',):
                raise ValueError("each list item must be one of ('all', 'data-property', 'value-domain', 'individual', 'annotation-property', 'universal_quantifier', 'complement', 'has-key')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RDFGraphConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in themes (list)
        _items = []
        if self.themes:
            for _item in self.themes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['themes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RDFGraphConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "themes": [Theme.from_dict(_item) for _item in obj.get("themes")] if obj.get("themes") is not None else None,
            "selectedTheme": obj.get("selectedTheme"),
            "language": obj.get("language"),
            "entityNameType": obj.get("entityNameType"),
            "renderers": obj.get("renderers"),
            "widgets": obj.get("widgets"),
            "filters": obj.get("filters")
        })
        return _obj


