# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ai_assistant.server.models.action import Action
from ai_assistant.server.models.class_instance_entity import ClassInstanceEntity
from ai_assistant.server.models.diagram import Diagram
from ai_assistant.server.models.grapholscape_entity import GrapholscapeEntity
from ai_assistant.server.models.rdf_graph_config import RDFGraphConfig
from ai_assistant.server.models.rdf_graph_metadata import RDFGraphMetadata
from ai_assistant.server.models.shacl_shape import SHACLShape
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RDFGraph(BaseModel):
    """
    RDFGraph
    """ # noqa: E501
    diagrams: List[Diagram]
    entities: List[GrapholscapeEntity]
    class_instance_entities: Optional[List[ClassInstanceEntity]] = Field(default=None, alias="classInstanceEntities")
    metadata: RDFGraphMetadata
    config: Optional[RDFGraphConfig] = None
    selected_diagram_id: Optional[StrictInt] = Field(default=0, alias="selectedDiagramId")
    model_type: StrictStr = Field(alias="modelType")
    actions: Optional[List[Action]] = None
    creator: Optional[StrictStr] = None
    constraints: Optional[List[SHACLShape]] = None
    __properties: ClassVar[List[str]] = ["diagrams", "entities", "classInstanceEntities", "metadata", "config", "selectedDiagramId", "modelType", "actions", "creator", "constraints"]

    @field_validator('model_type')
    def model_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('ontology', 'vkg', 'rdf',):
            raise ValueError("must be one of enum values ('ontology', 'vkg', 'rdf')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RDFGraph from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in diagrams (list)
        _items = []
        if self.diagrams:
            for _item in self.diagrams:
                if _item:
                    _items.append(_item.to_dict())
            _dict['diagrams'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in entities (list)
        _items = []
        if self.entities:
            for _item in self.entities:
                if _item:
                    _items.append(_item.to_dict())
            _dict['entities'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in class_instance_entities (list)
        _items = []
        if self.class_instance_entities:
            for _item in self.class_instance_entities:
                if _item:
                    _items.append(_item.to_dict())
            _dict['classInstanceEntities'] = _items
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item in self.actions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in constraints (list)
        _items = []
        if self.constraints:
            for _item in self.constraints:
                if _item:
                    _items.append(_item.to_dict())
            _dict['constraints'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RDFGraph from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "diagrams": [Diagram.from_dict(_item) for _item in obj.get("diagrams")] if obj.get("diagrams") is not None else None,
            "entities": [GrapholscapeEntity.from_dict(_item) for _item in obj.get("entities")] if obj.get("entities") is not None else None,
            "classInstanceEntities": [ClassInstanceEntity.from_dict(_item) for _item in obj.get("classInstanceEntities")] if obj.get("classInstanceEntities") is not None else None,
            "metadata": RDFGraphMetadata.from_dict(obj.get("metadata")) if obj.get("metadata") is not None else None,
            "config": RDFGraphConfig.from_dict(obj.get("config")) if obj.get("config") is not None else None,
            "selectedDiagramId": obj.get("selectedDiagramId") if obj.get("selectedDiagramId") is not None else 0,
            "modelType": obj.get("modelType"),
            "actions": [Action.from_dict(_item) for _item in obj.get("actions")] if obj.get("actions") is not None else None,
            "creator": obj.get("creator"),
            "constraints": [SHACLShape.from_dict(_item) for _item in obj.get("constraints")] if obj.get("constraints") is not None else None
        })
        return _obj


