# coding: utf-8

"""
    AI assistant API model

    This is the API for the AI assistant module

    The version of the OpenAPI document: 1.0.0
    Contact: info@obdasystems.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SHACLShape(BaseModel):
    """
    SHACLShape
    """ # noqa: E501
    id: Optional[StrictStr] = None
    type: StrictStr
    target_class: StrictStr = Field(alias="targetClass")
    path: StrictStr
    var_property: Optional[StrictStr] = Field(default=None, alias="property")
    constraint_value: Optional[List[StrictStr]] = Field(default=None, alias="constraintValue")
    __properties: ClassVar[List[str]] = ["id", "type", "targetClass", "path", "property", "constraintValue"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('Class', 'MinCount', 'MaxCount', 'MinExclusive', 'MaxExclusive', 'MinInclusive', 'MaxInclusive', 'MinLength', 'MaxLength', 'Pattern', 'In', 'Equals', 'Disjoint', 'LessThan', 'LessThanOrEquals',):
            raise ValueError("must be one of enum values ('Class', 'MinCount', 'MaxCount', 'MinExclusive', 'MaxExclusive', 'MinInclusive', 'MaxInclusive', 'MinLength', 'MaxLength', 'Pattern', 'In', 'Equals', 'Disjoint', 'LessThan', 'LessThanOrEquals')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SHACLShape from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SHACLShape from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "targetClass": obj.get("targetClass"),
            "path": obj.get("path"),
            "property": obj.get("property"),
            "constraintValue": obj.get("constraintValue")
        })
        return _obj


